#!/bin/bash
#Menu Original

#Donwload
wget -O /bin/menu https://raw.githubusercontent.com/Alefsousa5/SSH-PLUS-MANAGER/main/Modulos/menu > /dev/null 2>&1

#Permisos
chmod +x /bin/menu

#Ejecucion
/bin/menu

#fim